import json
import unittest
from io import BytesIO

from backend.app import ApiApp, ApiResponse
from backend.wsgi import make_wsgi_app


class EmptyRepository:
    def fetch_clubs(self):
        return []


class CaptureBodyApp:
    def __init__(self):
        self.captured = None

    def handle_request(self, **kwargs):
        self.captured = kwargs
        return ApiResponse(
            status_code=201,
            body=json.dumps({"body": kwargs["body"]}),
            headers={"Content-Type": "application/json; charset=utf-8"},
        )


class BackendWsgiTest(unittest.TestCase):
    def test_wsgi_adapter_serves_api_response(self):
        application = make_wsgi_app(ApiApp(repository=EmptyRepository(), jwt_secret="unit-test-secret"))
        captured = {}

        def start_response(status, headers):
            captured["status"] = status
            captured["headers"] = dict(headers)

        body = b"".join(application({
            "REQUEST_METHOD": "GET",
            "PATH_INFO": "/api/v1/health",
            "QUERY_STRING": "",
        }, start_response))

        self.assertEqual(captured["status"], "200 OK")
        self.assertEqual(captured["headers"]["Content-Type"], "application/json; charset=utf-8")
        self.assertEqual(json.loads(body.decode("utf-8")), {"status": "ok", "version": "v1"})

    def test_wsgi_adapter_forwards_client_request_id_through_to_api_app(self):
        # Regression test for audit #13: the WSGI adapter reconstructs header
        # names with str.title(), which turns the client's "X-Request-ID"
        # header into "X-Request-Id" ("ID" -> "Id"). This must not be
        # dropped/regenerated by ApiApp.handle_request due to a case-exact
        # header lookup - it must go through the real WSGI adapter (not a
        # direct handle_request(headers=...) call) to catch this bug.
        application = make_wsgi_app(ApiApp(repository=EmptyRepository(), jwt_secret="unit-test-secret"))
        captured = {}

        def start_response(status, headers):
            captured["status"] = status
            captured["headers"] = dict(headers)

        body = b"".join(application({
            "REQUEST_METHOD": "GET",
            "PATH_INFO": "/api/v1/no-such-endpoint",
            "QUERY_STRING": "",
            "HTTP_X_REQUEST_ID": "client-supplied-id-123",
        }, start_response))

        self.assertEqual(json.loads(body.decode("utf-8"))["error"]["requestId"], "client-supplied-id-123")

    def test_wsgi_adapter_passes_request_body_to_api_app(self):
        api_app = CaptureBodyApp()
        application = make_wsgi_app(api_app)
        captured = {}
        body_bytes = b'{"photoBase64":"cG9ydHJhaXQ="}'

        def start_response(status, headers):
            captured["status"] = status
            captured["headers"] = dict(headers)

        body = b"".join(application({
            "REQUEST_METHOD": "POST",
            "PATH_INFO": "/api/v1/me/ecp-requests",
            "QUERY_STRING": "",
            "CONTENT_LENGTH": str(len(body_bytes)),
            "wsgi.input": BytesIO(body_bytes),
        }, start_response))

        self.assertEqual(captured["status"], "201 Created")
        self.assertEqual(api_app.captured["body"], body_bytes.decode("utf-8"))
        self.assertEqual(json.loads(body.decode("utf-8")), {"body": body_bytes.decode("utf-8")})


if __name__ == "__main__":
    unittest.main()
